package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildTeamcity'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildTeamcity")) {
    expectSteps {
        script {
            name = "Command Line Runner Test"
            scriptContent = """
                #!/usr/bin/env bash
                VERSION=1.0
                echo ${'$'}VERSION >> test.txt
            """.trimIndent()
        }
        gradle {
            tasks = "printPro"
            gradleParams = "--info --stacktrace"
            gradleWrapperPath = ""
        }
    }
    steps {
        check(stepsOrder == arrayListOf("script.from.file.1")) {
            "Unexpected build steps order: $stepsOrder"
        }
        stepsOrder = arrayListOf("RUNNER_1", "RUNNER_2")
    }

    features {
        val feature1 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = personalToken {
                        token = "credentialsJSON:0daa7aae-da98-41c6-ab6f-bbbd9daefe83"
                    }
                }
                param("github_oauth_user", "gauravcanon")
            }
        }
        feature1.apply {
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = personalToken {
                    token = "credentialsJSON:30447dcd-21c2-4e73-b91f-faa658749e26"
                }
            }
        }
    }
}
