package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildTeamcity'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildTeamcity")) {
    params {
        add {
            param("env.PYTHONPATH", """C:\Users\gaura\AppData\Local\Programs\Python\Python39""")
        }
    }
}
